export const DataProject = [
    {
        id:"1",
        img:"/project1.webp",
        dish:"Web Designer",
        title:"Electronics and phone store",
        git:"https://github.com/ahmed26-coder/Shop-Project",
        live:"https://shop-project-mu-ecru.vercel.app/",
        language:"Java Script",
        description:"A clean and modern e-commerce store built with React Vite.js and Tailwind CSS. The website showcases a product listing interface with category filtering, responsive design across all devices, and smooth interactions. This project demonstrates strong front-end skills with a focus on layout, accessibility, and user experience.",
        technique:"React Vite.js",
    },
    {
        id:"2",
        img:"/project2.webp",
        dish:"Web Designer",
        title:"A website for selling courses online",
        git:"https://github.com/ahmed26-coder/Sourses",
        live:"https://sourses-online.vercel.app/",
        language:"Java Script",
        description:"An elegant and user-friendly platform for showcasing educational sources and tutorials. Built using React Vite.js and Tailwind CSS, the website features a responsive layout, categorized content cards, and a clean interface that enhances readability and navigation. This project highlights a strong grasp of component-based design and responsive front-end development.",
        technique:"React Vite.js",
    },
    {
        id:"3",
        img:"/project3.webp",
        dish:"Web Designer",
        title:"A site for donating money to the needy",
        git:"https://github.com/ahmed26-coder/Endeavor",
        live:"https://endeavor-one.vercel.app/",
        language:"Java Script",
        description:"Endeavor One is a sleek and intuitive web application designed for goal-setting and project management. Built with Next.js and Tailwind CSS, the platform allows users to track and manage their progress efficiently. The website features a modern, responsive layout and smooth user experience, ensuring a seamless interaction on both desktop and mobile devices.",
        technique:"Next.js",
    },
    {
        id:"4",
        img:"/project9.webp",
        dish:"Web Designer",
        title:"Website for selling or renting apartments",
        git:"https://github.com/ahmed26-coder/Meddical",
        live:"https://meddical-three.vercel.app/",
        language:"Type Script",
        description:"Meddical Three is a healthcare platform designed to provide users with easy access to medical services and information. Built with Next.js and Tailwind CSS, the website offers a clean, responsive interface that adapts to different devices. Features include easy navigation through medical topics, doctor listings, and a contact page, all aimed at improving user experience in the healthcare sector.",
        technique:"Next.js",
    },
];
export const DataProjects = [
    {
        id:"1",
        img:"/project1.webp",
        dish:"Web Designer",
        title:"Electronics and phone store",
        git:"https://github.com/ahmed26-coder/Shop-Project",
        live:"https://shop-project-mu-ecru.vercel.app/",
        description:"A clean and modern e-commerce store built with React Vite.js and Tailwind CSS. The website showcases a product listing interface with category filtering, responsive design across all devices, and smooth interactions. This project demonstrates strong front-end skills with a focus on layout, accessibility, and user experience.",
        language:"Java Script",
        technique:"React Vite.js",
    },
    {
        id:"2",
        img:"/project2.webp",
        dish:"Web Designer",
        title:"A website for selling courses online",
        git:"https://github.com/ahmed26-coder/Sourses",
        live:"https://sourses-online.vercel.app/",
        description:"An elegant and user-friendly platform for showcasing educational sources and tutorials. Built using React Vite.js and Tailwind CSS, the website features a responsive layout, categorized content cards, and a clean interface that enhances readability and navigation. This project highlights a strong grasp of component-based design and responsive front-end development.",
        language:"Java Script",
        technique:"React Vite.js",
    },
    {
        id:"3",
        img:"/project3.webp",
        dish:"Web Designer",
        title:"A site for donating money to the needy",
        git:"https://github.com/ahmed26-coder/Endeavor",
        live:"https://endeavor-one.vercel.app/",
        description:"Endeavor One is a sleek and intuitive web application designed for goal-setting and project management. Built with Next.js and Tailwind CSS, the platform allows users to track and manage their progress efficiently. The website features a modern, responsive layout and smooth user experience, ensuring a seamless interaction on both desktop and mobile devices.",
        language:"Java Script",
        technique:"Next.js",
    },
    {
        id:"4",
        img:"/project4.webp",
        dish:"Web Designer",
        title:"Website for selling or renting apartments",
        git:"https://github.com/ahmed26-coder/Logoipsum",
        live:"https://logoipsum-lime-eight.vercel.app/",
        description:"Logo Ipsum is a fun and creative tool designed to generate random placeholder logos for projects. Whether you're designing a website, an app, or any other project, Logo Ipsum provides users with customizable logos that can be used as placeholders. Built using Next.js, the website offers a seamless, easy-to-use interface that allows users to instantly generate logos for any purpose.",
        language:"Java Script",
        technique:"Next.js",
    },
    {
        id:"5",
        img:"/project5.webp",
        dish:"Web Designer",
        title:"Air travel website",
        git:"https://github.com/ahmed26-coder/Triptopia",
        live:"https://triptopia.vercel.app/",
        description:"Triptopia is a travel website designed to help users discover the best travel destinations and plan their trips with ease. The site features a sleek, user-friendly interface where users can explore various travel destinations, view detailed information about each location, and find the best travel offers. Built with Next.js and Tailwind CSS, Triptopia provides a seamless experience across all devices, making it easy for travelers to plan their next adventure.",
        language:"Java Script",
        technique:"Next.js",
    },
    {
        id:"6",
        img:"/project6.webp",
        dish:"Web Designer",
        title:"A website for booking and communicating with doctors",
        git:"https://github.com/ahmed26-coder/Health-Point",
        live:"https://health-point-one.vercel.app/",
        description:"Health Point is a health-focused website designed to provide users with essential health-related information and resources. Whether you're looking for wellness tips, medical advice, or the latest health news, Health Point offers a user-friendly platform to stay informed. Built with Next.js and Tailwind CSS, the website delivers a seamless experience, helping users take charge of their health and well-being.",
        language:"Java Script",
        technique:"Next.js",
    },
    {
        id:"7",
        img:"/project7.webp",
        dish:"Web Designer",
        title:"NFC selling site",
        git:"https://github.com/ahmed26-coder/NFC-Marketplace",
        live:"https://nfc-marketplace-neon.vercel.app/",
        description:"NFC Marketplace is a cutting-edge platform that allows users to buy and sell Non-Fungible Tokens (NFTs) in a decentralized marketplace. The website offers a sleek, modern interface where users can explore various digital assets, including art, collectibles, and more. Built with Next.js and integrated with Web3 technologies, NFC Marketplace enables secure transactions on the blockchain. The platform also features easy navigation, real-time updates, and seamless wallet integration for a smooth user experience.",
        language:"Java Script",
        technique:"Next.js",
    },
    {
        id:"8",
        img:"/project9.webp",
        dish:"Web Designer",
        title:"Doctors website",
        git:"https://github.com/ahmed26-coder/Meddical",
        live:"https://meddical-three.vercel.app/",
        description:"Meddical Three is a healthcare platform designed to provide users with easy access to medical services and information. Built with Next.js and Tailwind CSS, the website offers a clean, responsive interface that adapts to different devices. Features include easy navigation through medical topics, doctor listings, and a contact page, all aimed at improving user experience in the healthcare sector.",
        language:"Type Script",
        technique:"Next.js",
    },
    {
        id:"9",
        img:"/project10.webp",
        dish:"Web Designer",
        title:"online store",
        git:"https://github.com/ahmed26-coder/Mega-Mark",
        live:"https://mega-mark.vercel.app/",
        description:"Mega Mark is an e-commerce platform designed to provide a seamless shopping experience for users. The website offers a variety of products, including fashion, electronics, and more. With its modern UI and smooth navigation, Mega Mark helps users easily browse, add products to their cart, and make purchases online. The platform is built using Next.js and Tailwind CSS, ensuring responsive design and optimized performance across devices. Mega Mark also features user authentication and payment integration for a fully functional online store.",
        language:"Type Script",
        technique:"Next.js",
    },
    
];
export const DataSkills = [
    {
        id:"1",
        img:"/html.webp",
        title:"Html",
    },
    {
        id:"2",
        img:"/css3.svg",
        title:"Css",
    },
    {
        id:"3",
        img:"/javascript.svg",
        title:"Java Script",
    },
    {
        id:"4",
        img:"/TS-removebg-preview.webp",
        title:"Type Script",
    },
    {
        id:"5",
        img:"/react.svg",
        title:"React.js",
    },
    {
        id:"6",
        img:"/next.webp",
        title:"Next.js",
    },
    {
        id:"7",
        img:"/redux.png",
        title:"Redux",
    },
    {
        id:"8",
        img:"/tailwindcss.svg",
        title:" Tailwind CSS",
    },
    {
        id:"9",
        img:"/sass.webp",
        title:"Sass",
    },
    {
        id:"10",
        img:"/MUI-removebg-preview.webp",
        title:"MUi",
    },
    {
        id:"11",
        img:"/motion.webp",
        title:"Framer Motion",
    },
    {
        id:"12",
        img:"/gsap.svg",
        title:"GSAP",
    },
    {
        id:"13",
        img:"/shadcn.webp",
        title:"Shadcn/ui",
    },
    {
        id:"14",
        img:"/git.webp",
        title:"Git",
    },
    {
        id:"15",
        img:"/figma.svg",
        title:"Figma",
    },
    {
        id:"16",
        img:"/axios.webp",
        title:"axios",
    }
];
import { FaGithub, FaLinkedin } from "react-icons/fa";
import { IoLogoWhatsapp } from "react-icons/io5";
  export const socialLinks = [
    { id:"1", href: "https://wa.me/201016626452", title:"Whats app", icon:<IoLogoWhatsapp/> },
    { id:"2", href: "https://www.linkedin.com/in/ahmed-adham-479334331/", title:"Linkedin", icon:<FaLinkedin/> },
    { id:"3", href: "https://github.com/ahmed26-coder",title:"github", icon:<FaGithub/> },
  ];